### PR TITLE
Please review

### PR DESCRIPTION
**Pull request by dallenk**
Using your most recent code, I added my menu and mapping options.. it's been a few months so I hope I'm going the pull request correctly...

### CODE REVIEW

**Comment by softcoder** [comment]
Shows that you need to merge conflicts with your pull request

**Comment by dallenk** [comment]
I have no idea how to do that lol.. I scrapped windows and running linux 
now on my laptop.. so learning a new software package now...

**Comment by dallenk** [comment]
ok.. this git is being a real pain in the ass... How can I easily refork 
to my own repository then commit my changes..  every time i read the 
docs and try it something goes awry....  I'm now 9 commits ahead of you, 
and 32 behind.. and my latest one ignored all my ignore settings so a 
crap load of files that weren't supposed to be uploaded, got uploaded..

**Comment by softcoder** [comment]
If you want you could zip your whole folder and email it to me
then i could try to merge it locally and push to github?

Thanks

**Comment by dallenk** [comment]
i'm in the middle of one more change I missed.. i'll give it another 
shot.. I may have figured it out after reading for a couple hours. hah

**Pull request closed without merging**
